// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";

export const Operator: autoguard.serialization.MessageGuard<Operator> = autoguard.guards.Union.of(
	autoguard.guards.StringLiteral.of(">"),
	autoguard.guards.StringLiteral.of(">="),
	autoguard.guards.StringLiteral.of("=="),
	autoguard.guards.StringLiteral.of("!="),
	autoguard.guards.StringLiteral.of("<"),
	autoguard.guards.StringLiteral.of("<=")
);

export type Operator = autoguard.guards.Union<[
	autoguard.guards.StringLiteral<">">,
	autoguard.guards.StringLiteral<">=">,
	autoguard.guards.StringLiteral<"==">,
	autoguard.guards.StringLiteral<"!=">,
	autoguard.guards.StringLiteral<"<">,
	autoguard.guards.StringLiteral<"<=">
]>;

export const IntegerOperator: autoguard.serialization.MessageGuard<IntegerOperator> = autoguard.guards.Reference.of(() => Operator);

export type IntegerOperator = autoguard.guards.Reference<Operator>;

export const WhereInteger: autoguard.serialization.MessageGuard<WhereInteger> = autoguard.guards.Object.of({
	"key": autoguard.guards.String,
	"operator": autoguard.guards.Reference.of(() => IntegerOperator),
	"operand": autoguard.guards.Union.of(
		autoguard.guards.Integer,
		autoguard.guards.Null
	)
}, {});

export type WhereInteger = autoguard.guards.Object<{
	"key": autoguard.guards.String,
	"operator": autoguard.guards.Reference<IntegerOperator>,
	"operand": autoguard.guards.Union<[
		autoguard.guards.Integer,
		autoguard.guards.Null
	]>
}, {}>;

export const StringOperator: autoguard.serialization.MessageGuard<StringOperator> = autoguard.guards.Union.of(
	autoguard.guards.Reference.of(() => Operator),
	autoguard.guards.StringLiteral.of("^="),
	autoguard.guards.StringLiteral.of("*="),
	autoguard.guards.StringLiteral.of("$=")
);

export type StringOperator = autoguard.guards.Union<[
	autoguard.guards.Reference<Operator>,
	autoguard.guards.StringLiteral<"^=">,
	autoguard.guards.StringLiteral<"*=">,
	autoguard.guards.StringLiteral<"$=">
]>;

export const WhereString: autoguard.serialization.MessageGuard<WhereString> = autoguard.guards.Object.of({
	"key": autoguard.guards.String,
	"operator": autoguard.guards.Reference.of(() => StringOperator),
	"operand": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Null
	)
}, {});

export type WhereString = autoguard.guards.Object<{
	"key": autoguard.guards.String,
	"operator": autoguard.guards.Reference<StringOperator>,
	"operand": autoguard.guards.Union<[
		autoguard.guards.String,
		autoguard.guards.Null
	]>
}, {}>;

export const BooleanOperator: autoguard.serialization.MessageGuard<BooleanOperator> = autoguard.guards.Reference.of(() => Operator);

export type BooleanOperator = autoguard.guards.Reference<Operator>;

export const WhereBoolean: autoguard.serialization.MessageGuard<WhereBoolean> = autoguard.guards.Object.of({
	"key": autoguard.guards.String,
	"operator": autoguard.guards.Reference.of(() => BooleanOperator),
	"operand": autoguard.guards.Union.of(
		autoguard.guards.Boolean,
		autoguard.guards.Null
	)
}, {});

export type WhereBoolean = autoguard.guards.Object<{
	"key": autoguard.guards.String,
	"operator": autoguard.guards.Reference<BooleanOperator>,
	"operand": autoguard.guards.Union<[
		autoguard.guards.Boolean,
		autoguard.guards.Null
	]>
}, {}>;

export const DateOperator: autoguard.serialization.MessageGuard<DateOperator> = autoguard.guards.Reference.of(() => Operator);

export type DateOperator = autoguard.guards.Reference<Operator>;

export const WhereDate: autoguard.serialization.MessageGuard<WhereDate> = autoguard.guards.Object.of({
	"key": autoguard.guards.String,
	"operator": autoguard.guards.Reference.of(() => DateOperator),
	"operand": autoguard.guards.Union.of(
		autoguard.guards.Date,
		autoguard.guards.Null
	)
}, {});

export type WhereDate = autoguard.guards.Object<{
	"key": autoguard.guards.String,
	"operator": autoguard.guards.Reference<DateOperator>,
	"operand": autoguard.guards.Union<[
		autoguard.guards.Date,
		autoguard.guards.Null
	]>
}, {}>;

export const WhereAll: autoguard.serialization.MessageGuard<WhereAll> = autoguard.guards.Object.of({
	"all": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Where))
}, {});

export type WhereAll = autoguard.guards.Object<{
	"all": autoguard.guards.Array<autoguard.guards.Reference<Where>>
}, {}>;

export const WhereAny: autoguard.serialization.MessageGuard<WhereAny> = autoguard.guards.Object.of({
	"any": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Where))
}, {});

export type WhereAny = autoguard.guards.Object<{
	"any": autoguard.guards.Array<autoguard.guards.Reference<Where>>
}, {}>;

export const WhereNot: autoguard.serialization.MessageGuard<WhereNot> = autoguard.guards.Object.of({
	"not": autoguard.guards.Reference.of(() => Where)
}, {});

export type WhereNot = autoguard.guards.Object<{
	"not": autoguard.guards.Reference<Where>
}, {}>;

export const Where: autoguard.serialization.MessageGuard<Where> = autoguard.guards.Union.of(
	autoguard.guards.Reference.of(() => WhereInteger),
	autoguard.guards.Reference.of(() => WhereString),
	autoguard.guards.Reference.of(() => WhereBoolean),
	autoguard.guards.Reference.of(() => WhereDate),
	autoguard.guards.Reference.of(() => WhereAll),
	autoguard.guards.Reference.of(() => WhereAny),
	autoguard.guards.Reference.of(() => WhereNot)
);

export type Where = autoguard.guards.Union<[
	autoguard.guards.Reference<WhereInteger>,
	autoguard.guards.Reference<WhereString>,
	autoguard.guards.Reference<WhereBoolean>,
	autoguard.guards.Reference<WhereDate>,
	autoguard.guards.Reference<WhereAll>,
	autoguard.guards.Reference<WhereAny>,
	autoguard.guards.Reference<WhereNot>
]>;

export const Sort: autoguard.serialization.MessageGuard<Sort> = autoguard.guards.Union.of(
	autoguard.guards.StringLiteral.of("ASC"),
	autoguard.guards.StringLiteral.of("DESC")
);

export type Sort = autoguard.guards.Union<[
	autoguard.guards.StringLiteral<"ASC">,
	autoguard.guards.StringLiteral<"DESC">
]>;

export const Order: autoguard.serialization.MessageGuard<Order> = autoguard.guards.Object.of({
	"keys": autoguard.guards.Array.of(autoguard.guards.String),
	"sort": autoguard.guards.Reference.of(() => Sort)
}, {});

export type Order = autoguard.guards.Object<{
	"keys": autoguard.guards.Array<autoguard.guards.String>,
	"sort": autoguard.guards.Reference<Sort>
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"Operator": autoguard.guards.Reference.of(() => Operator),
		"IntegerOperator": autoguard.guards.Reference.of(() => IntegerOperator),
		"WhereInteger": autoguard.guards.Reference.of(() => WhereInteger),
		"StringOperator": autoguard.guards.Reference.of(() => StringOperator),
		"WhereString": autoguard.guards.Reference.of(() => WhereString),
		"BooleanOperator": autoguard.guards.Reference.of(() => BooleanOperator),
		"WhereBoolean": autoguard.guards.Reference.of(() => WhereBoolean),
		"DateOperator": autoguard.guards.Reference.of(() => DateOperator),
		"WhereDate": autoguard.guards.Reference.of(() => WhereDate),
		"WhereAll": autoguard.guards.Reference.of(() => WhereAll),
		"WhereAny": autoguard.guards.Reference.of(() => WhereAny),
		"WhereNot": autoguard.guards.Reference.of(() => WhereNot),
		"Where": autoguard.guards.Reference.of(() => Where),
		"Sort": autoguard.guards.Reference.of(() => Sort),
		"Order": autoguard.guards.Reference.of(() => Order)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
