// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";

export const Object: autoguard.serialization.MessageGuard<Object> = autoguard.guards.Object.of({
	"object_id": autoguard.guards.String,
	"optional_boolean": autoguard.guards.Union.of(
		autoguard.guards.Boolean,
		autoguard.guards.Null
	),
	"optional_integer": autoguard.guards.Union.of(
		autoguard.guards.Integer,
		autoguard.guards.Null
	),
	"optional_string": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Null
	)
}, {});

export type Object = autoguard.guards.Object<{
	"object_id": autoguard.guards.String,
	"optional_boolean": autoguard.guards.Union<[
		autoguard.guards.Boolean,
		autoguard.guards.Null
	]>,
	"optional_integer": autoguard.guards.Union<[
		autoguard.guards.Integer,
		autoguard.guards.Null
	]>,
	"optional_string": autoguard.guards.Union<[
		autoguard.guards.String,
		autoguard.guards.Null
	]>
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"Object": autoguard.guards.Reference.of(() => Object)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
